# Generated by Django 5.2 on 2025-04-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_guest_reservation'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS raw_data (
                    datetime     TIMESTAMPTZ NOT NULL,
                    device_id    TEXT NOT NULL,
                    datapoint    TEXT NOT NULL,
                    value        FLOAT
                );
                SELECT create_hypertable('raw_data', 'datetime', if_not_exists => TRUE);
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS raw_data;
            """
        )
    ]
