version: '3.8'

services:
  smartHotel_db:
    image: timescale/timescaledb:latest-pg14
    container_name: smartHotel_db
    ports:
      - "${PG_PORT}:5432" 
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - smartHotel_db_data:/var/lib/postgresql/data
    networks:
      - smarthotel_network
    restart: unless-stopped
    command: >
      postgres
      -c shared_preload_libraries=timescaledb

  smartHotel_rabbitmq:
    image: rabbitmq:3-management
    container_name: smartHotel_rabbitmq
    ports:
      - "${RABBITMQ_BROKER_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - smarthotel_network
    restart: unless-stopped

  smartHotel_pgadmin:
    image: dpage/pgadmin4
    container_name: smartHotel_pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - smartHotel_pgadmin_data:/var/lib/pgadmin
    networks:
      - smarthotel_network
    restart: unless-stopped

volumes:
  smartHotel_db_data:
  smartHotel_pgadmin_data:

networks:
  smarthotel_network:
    external: true
